### ISSUE TITLE
get "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by faddah** [Maqentaer/dom2jsonml#1]
hello @Maqentaer ,

i have node v0.10.36 and npm 2.7.1 installed and i used npm to install your latest version of dom2jsonml.

when i install your module with `npm install -g dom2jsonml` and then try to include it in my JavaScript file that gets called from an HTML file (the HTML file i'm trying to parse into JSON), i get in the JavaScript Console on Chrome browser —

``` bash

Uncaught ReferenceError: require is not defined

```

here is my HTML —

``` HTML

 <!DOCTYPE HTML>
<html>
  <head>
    <title>The Tree Walker DOM Example Page</title>
  </head>
  <body>
    <div>
      <h1>The Tree Walker</h1>
    </div>
    <ul id="mylist">
      <li>List Item 1</li>
      <li>List Item 2</li>
      <li>List Item 3</li>
    </ul>


    <div id="DOM-tree">

    </div>

    <div id="final-result">
    </div>

    <script src="dom2json.js" type="text/javascript"></script>
  </body>
</html>

```

and here is my JavaScript file — 

``` JavaScript

var dom2jsonml = require('dom2jsonml');

var jsonMl = dom2jsonml(window.document.documentElement);

if(null === jsonMl) {
  throw new Error("Invalid DOM");
} else {
  document.getElementById("final-result").innerHTML = JSON.stringify(jsonML);
  console.log(JSON.stringify(jsonMl));
}

```

as you can see, most of my JS file above is taken directly from your example at npmjs.com, i just am choosing to start from the `documentElement`, or the root node (`<html>`), instead of the body, to see the whole tree.

any help as to why this is happening would be appreciated.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by Maqentaer** [comment]
Hello @faddah,

For using notejs modules inside browsers you should use **Browserify**: http://browserify.org/
But in your case you can use simple [jsonml-dom.js](https://raw.githubusercontent.com/mckamey/jsonml/master/jsonml-dom.js). See more scripts and more info on http://www.jsonml.org/

## 

Best regards,
Roman.

**Comment by faddah** [comment]
@Maqentaer - thanx! i will check those out. unless i run into similar issues with browserify or jsonml-dom.js and have to post here again, o.k. to close this out. thank you for the help.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by faddah** [comment]
@Maqentaer - browserify did it for me, so ok to close this out.
